// AUTO-GENERATED by proofhouse.compiler.codegen.typescript. Do not edit by hand.
// Source: https://proofhouse.dev/schemas/ir/0.1.0

export type NonEmpty = string;
export type Identifier = string;
export type Sha256 = string;
export type NonEmptyStringArray = NonEmpty[];
export type Capabilities = string[];

export interface JsonSchema {
  [key: string]: unknown;
}

export interface DataContract {
  id: Identifier;
  name: NonEmpty;
  required: boolean;
  schema: JsonSchema;
}

export interface Requirement {
  id: string;
  statement: NonEmpty;
  priority: "p0" | "p1" | "p2";
  mandatory: boolean;
  acceptance: NonEmptyStringArray;
}

export interface PolicyBlock {
  rules: NonEmptyStringArray;
}

export interface ProofhouseIRProject {
  name: NonEmpty;
  description?: string;
  mode: "creative" | "balanced" | "enterprise";
  compilation_level: "prompt" | "prompt_system" | "agent_blueprint" | "application_specification";
}

export interface ProofhouseIRObjective {
  goal: NonEmpty;
  target_users: NonEmptyStringArray;
  success_criteria: NonEmptyStringArray;
  failure_conditions: NonEmptyStringArray;
}

export interface ProofhouseIRBehavior {
  instructions: NonEmptyStringArray;
  constraints: NonEmptyStringArray;
  uncertainty_policy: NonEmpty;
  evidence_policy: NonEmpty;
}

export interface ProofhouseIRKnowledgeSourcesItem {
  id: Identifier;
  kind: "inline" | "file" | "retrieval_snapshot";
  required: boolean;
  sha256?: Sha256;
}

export interface ProofhouseIRKnowledge {
  sources: ProofhouseIRKnowledgeSourcesItem[];
}

export interface ProofhouseIRMemory {
  mode: "none" | "session" | "persistent";
  retention: NonEmpty;
  sensitive_data_allowed?: boolean;
}

export interface ProofhouseIRToolsItem {
  id: Identifier;
  description: NonEmpty;
  input_schema: JsonSchema;
  output_schema?: JsonSchema;
  side_effecting: boolean;
  approval: "never" | "policy" | "always";
}

export interface ProofhouseIRWorkflowStepsItem {
  id: Identifier;
  action: NonEmpty;
  on_failure: "stop" | "continue" | "request_approval";
}

export interface ProofhouseIRWorkflow {
  steps: ProofhouseIRWorkflowStepsItem[];
}

export interface ProofhouseIRAutonomy {
  approval_policy: "read_only" | "bounded_write" | "human_approval";
  max_tool_calls: number;
  stop_conditions?: NonEmptyStringArray;
}

export interface ProofhouseIRProviderRequirements {
  required_capabilities: Capabilities;
  optional_capabilities: Capabilities;
}

export interface ProofhouseIREvaluation {
  dimensions: NonEmptyStringArray;
  repair_limit: number;
  baseline_required: boolean;
  test_categories: NonEmptyStringArray;
}

export interface ProofhouseIRDeployment {
  targets: NonEmptyStringArray;
}

export interface ProofhouseIRProvenance {
  source_id: NonEmpty;
  source_sha256: Sha256;
}

export interface ProofhouseIR {
  spec_version: "0.1.0";
  project: ProofhouseIRProject;
  objective: ProofhouseIRObjective;
  requirements: Requirement[];
  input_contracts?: DataContract[];
  output_contracts?: DataContract[];
  behavior: ProofhouseIRBehavior;
  knowledge?: ProofhouseIRKnowledge;
  memory?: ProofhouseIRMemory;
  tools?: ProofhouseIRToolsItem[];
  workflow?: ProofhouseIRWorkflow;
  autonomy?: ProofhouseIRAutonomy;
  security?: PolicyBlock;
  privacy?: PolicyBlock;
  provider_requirements?: ProofhouseIRProviderRequirements;
  evaluation: ProofhouseIREvaluation;
  deployment?: ProofhouseIRDeployment;
  assumptions?: NonEmpty[];
  open_questions?: NonEmpty[];
  provenance: ProofhouseIRProvenance;
}
