"""Reproducible JSON-Schema -> TypeScript generation for the boundary
contracts. Deliberately minimal (no external codegen dependency, no
network): handles exactly the schema shapes used by the frozen IR and
diagnostic contract schemas -- object/array/string/integer/boolean,
$ref into $defs, const, and enum. Output is deterministic: identical
input always produces byte-identical output, so drift can be detected
with a plain diff (see test_typescript_generation.py).
"""
from __future__ import annotations

import json
import re
from pathlib import Path

_VALID_IDENT_RE = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")
_WORD_SPLIT_RE = re.compile(r"[_\-]+")


def _pascal(name: str) -> str:
    parts = [p for p in _WORD_SPLIT_RE.split(name) if p]
    return "".join(p[:1].upper() + p[1:] for p in parts)


def _ts_key(name: str) -> str:
    return name if _VALID_IDENT_RE.match(name) else json.dumps(name)


class _Generator:
    def __init__(self, schema: dict, root_name: str):
        self.schema = schema
        self.root_name = root_name
        self.defs: dict = schema.get("$defs", {})
        self.def_names = {key: _pascal(key) for key in self.defs}
        self.interfaces: dict[str, str] = {}
        self.def_type_aliases: dict[str, str] = {}

    def generate(self) -> str:
        for key, subschema in self.defs.items():
            name = self.def_names[key]
            self.def_type_aliases[name] = self._type_expr(subschema, name)

        root_expr = self._type_expr(self.schema, self.root_name)
        if self.root_name not in self.interfaces:
            # Root schema was not an object (unexpected for our contracts, but
            # keep this reproducible rather than silently dropping it).
            self.def_type_aliases[self.root_name] = root_expr

        lines = [
            "// AUTO-GENERATED by proofhouse.compiler.codegen.typescript. Do not edit by hand.",
            f"// Source: {self.schema.get('$id', '<unknown>')}",
            "",
        ]
        for name, expr in self.def_type_aliases.items():
            if name in self.interfaces:
                continue
            lines.append(f"export type {name} = {expr};")
        if any(name not in self.interfaces for name in self.def_type_aliases):
            lines.append("")
        for name, body in self.interfaces.items():
            lines.append(f"export interface {name} {{")
            lines.append(body)
            lines.append("}")
            lines.append("")
        return "\n".join(lines).rstrip() + "\n"

    def _ref_name(self, ref: str) -> str:
        key = ref.rsplit("/", 1)[-1]
        return self.def_names[key]

    def _type_expr(self, subschema: dict, name_hint: str) -> str:
        if "$ref" in subschema:
            return self._ref_name(subschema["$ref"])
        if "const" in subschema:
            return json.dumps(subschema["const"])
        if "enum" in subschema:
            return " | ".join(json.dumps(v) for v in subschema["enum"])

        t = subschema.get("type")
        if t == "object" or (t is None and "properties" in subschema):
            return self._object_type(subschema, name_hint)
        if t == "array":
            items = subschema.get("items")
            item_expr = self._type_expr(items, name_hint + "Item") if items else "unknown"
            return f"{item_expr}[]"
        if t == "string":
            return "string"
        if t in ("integer", "number"):
            return "number"
        if t == "boolean":
            return "boolean"
        return "unknown"

    def _object_type(self, subschema: dict, name_hint: str) -> str:
        interface_name = _pascal(name_hint)
        base_name = interface_name
        suffix = 1
        while interface_name in self.interfaces:
            suffix += 1
            interface_name = f"{base_name}{suffix}"

        properties: dict = subschema.get("properties", {})
        required = set(subschema.get("required", []))
        field_lines = []
        for prop_name, prop_schema in properties.items():
            field_type = self._type_expr(prop_schema, f"{interface_name}_{prop_name}")
            optional = "" if prop_name in required else "?"
            field_lines.append(f"  {_ts_key(prop_name)}{optional}: {field_type};")
        if not properties and subschema.get("type") == "object":
            field_lines.append("  [key: string]: unknown;")

        self.interfaces[interface_name] = "\n".join(field_lines) if field_lines else "  [key: string]: unknown;"
        return interface_name


def generate_typescript(schema: dict, root_name: str) -> str:
    return _Generator(schema, root_name).generate()


def generate_all(*, ir_schema_path: Path, diagnostic_schema_path: Path) -> dict[str, str]:
    """Returns {relative_output_filename: generated_ts_source}."""
    ir_schema = json.loads(ir_schema_path.read_text(encoding="utf-8"))
    diagnostic_schema = json.loads(diagnostic_schema_path.read_text(encoding="utf-8"))
    return {
        "proofhouse_ir.ts": generate_typescript(ir_schema, "ProofhouseIR"),
        "diagnostic.ts": generate_typescript(diagnostic_schema, "Diagnostic"),
    }
